# Formulação matemática ACDM

In [1]:
import Pkg; Pkg.add("JuMP")

  Updating registry at `C:\Users\Catarina\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % Resolving package versions...
  Updating `C:\Users\Catarina\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Catarina\.julia\environments\v1.1\Manifest.toml`
 [no changes]


In [2]:
Pkg.add("GLPK")

 Resolving package versions...
  Updating `C:\Users\Catarina\.julia\environments\v1.1\Project.toml`
 [no changes]
  Updating `C:\Users\Catarina\.julia\environments\v1.1\Manifest.toml`
 [no changes]


In [3]:
 using LinearAlgebra

In [4]:
using JuMP

In [5]:
using GLPKMathProgInterface


In [6]:
using GLPK

In [7]:
file_name = "trsp_50_1.dat"

"trsp_50_1.dat"

In [8]:
file = open(file_name)

IOStream(<file trsp_50_1.dat>)

In [9]:
lines = readlines(file)

51-element Array{String,1}:
 "50"
 "91"
 "38"
 "58"
 "16"
 "5" 
 "28"
 "35"
 "95"
 "18"
 "27"
 "38"
 "74"
 ⋮   
 "18"
 "65"
 "86"
 "58"
 "7" 
 "55"
 "99"
 "4" 
 "62"
 "40"
 "81"
 "74"

In [10]:
close(file)

In [11]:
firstLine = split(lines[1])
n = parse(Int64, firstLine[1])
p = zeros(n)
#p = transpose(p)

50-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [12]:
for i=1:n
    line_to_read = split(lines[i+1])
    p[i] = parse(Float64, line_to_read[1]) 
end

In [13]:
xij = Matrix{Int64}(I, n, n)

50×50 Array{Int64,2}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  1  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  1  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1    

In [14]:
for i=1:n
    for j=1:n
       xij[i, j] = min(p[i], p[j])
       xij[j, i] = min(p[i], p[j])
    end
end

In [15]:
M = sum(p[i] for i in 1:n) #+ xij[i, j]

2705.0

In [16]:
m = Model(with_optimizer(GLPK.Optimizer))

A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK

In [17]:
@variable(m, dij[1:n,1:n],Bin)

50×50 Array{VariableRef,2}:
 dij[1,1]   dij[1,2]   dij[1,3]   …  dij[1,48]   dij[1,49]   dij[1,50] 
 dij[2,1]   dij[2,2]   dij[2,3]      dij[2,48]   dij[2,49]   dij[2,50] 
 dij[3,1]   dij[3,2]   dij[3,3]      dij[3,48]   dij[3,49]   dij[3,50] 
 dij[4,1]   dij[4,2]   dij[4,3]      dij[4,48]   dij[4,49]   dij[4,50] 
 dij[5,1]   dij[5,2]   dij[5,3]      dij[5,48]   dij[5,49]   dij[5,50] 
 dij[6,1]   dij[6,2]   dij[6,3]   …  dij[6,48]   dij[6,49]   dij[6,50] 
 dij[7,1]   dij[7,2]   dij[7,3]      dij[7,48]   dij[7,49]   dij[7,50] 
 dij[8,1]   dij[8,2]   dij[8,3]      dij[8,48]   dij[8,49]   dij[8,50] 
 dij[9,1]   dij[9,2]   dij[9,3]      dij[9,48]   dij[9,49]   dij[9,50] 
 dij[10,1]  dij[10,2]  dij[10,3]     dij[10,48]  dij[10,49]  dij[10,50]
 dij[11,1]  dij[11,2]  dij[11,3]  …  dij[11,48]  dij[11,49]  dij[11,50]
 dij[12,1]  dij[12,2]  dij[12,3]     dij[12,48]  dij[12,49]  dij[12,50]
 dij[13,1]  dij[13,2]  dij[13,3]     dij[13,48]  dij[13,49]  dij[13,50]
 ⋮                                ⋱ 

In [18]:
@variable(m, T >=0, Int)

T

In [19]:
@variable(m, s[1:n] >=0, Int)

50-element Array{VariableRef,1}:
 s[1] 
 s[2] 
 s[3] 
 s[4] 
 s[5] 
 s[6] 
 s[7] 
 s[8] 
 s[9] 
 s[10]
 s[11]
 s[12]
 s[13]
 ⋮    
 s[39]
 s[40]
 s[41]
 s[42]
 s[43]
 s[44]
 s[45]
 s[46]
 s[47]
 s[48]
 s[49]
 s[50]

In [20]:
@objective(m, Min, T) 

T

In [23]:
@constraint(m, [i in 1:n, j in 1:n], s[i] >= xij[i,j] + s[j] - M * (1 - dij[i,j]))

50×50 Array{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,2}:
 -2705 dij[1,1] >= -2614.0                 …  s[1] - s[50] - 2705 dij[1,50] >= -2631.0  
 s[2] - s[1] - 2705 dij[2,1] >= -2667.0       s[2] - s[50] - 2705 dij[2,50] >= -2667.0  
 s[3] - s[1] - 2705 dij[3,1] >= -2647.0       s[3] - s[50] - 2705 dij[3,50] >= -2647.0  
 s[4] - s[1] - 2705 dij[4,1] >= -2689.0       s[4] - s[50] - 2705 dij[4,50] >= -2689.0  
 s[5] - s[1] - 2705 dij[5,1] >= -2700.0       s[5] - s[50] - 2705 dij[5,50] >= -2700.0  
 s[6] - s[1] - 2705 dij[6,1] >= -2677.0    …  s[6] - s[50] - 2705 dij[6,50] >= -2677.0  
 s[7] - s[1] - 2705 dij[7,1] >= -2670.0       s[7] - s[50] - 2705 dij[7,50] >= -2670.0  
 s[8] - s[1] - 2705 dij[8,1] >= -2614.0       s[8] - s[50] - 2705 dij[8,50] >= -2631.0  
 s[9] - s[1] - 2705 dij[9,1] >= -2687.0       s[9] - s[50] - 2705 dij[9,50] >= -2687.0  
 s[10] - s[1] - 2705 dij[10,1] >= -2678.0     s[10] - s[50] - 2705 dij[10,50] >= -2678.0
 s[11] - s[1] - 2705 dij[11,1]

In [24]:
@constraint(m, [i in 1:n], T >= s[i] + p[i]) 

50-element Array{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,1}:
 T - s[1] >= 91.0 
 T - s[2] >= 38.0 
 T - s[3] >= 58.0 
 T - s[4] >= 16.0 
 T - s[5] >= 5.0  
 T - s[6] >= 28.0 
 T - s[7] >= 35.0 
 T - s[8] >= 95.0 
 T - s[9] >= 18.0 
 T - s[10] >= 27.0
 T - s[11] >= 38.0
 T - s[12] >= 74.0
 T - s[13] >= 73.0
 ⋮                
 T - s[39] >= 18.0
 T - s[40] >= 65.0
 T - s[41] >= 86.0
 T - s[42] >= 58.0
 T - s[43] >= 7.0 
 T - s[44] >= 55.0
 T - s[45] >= 99.0
 T - s[46] >= 4.0 
 T - s[47] >= 62.0
 T - s[48] >= 40.0
 T - s[49] >= 81.0
 T - s[50] >= 74.0

In [25]:
@constraint(m, [i in 1:n, j in 1:n], dij[i,j] + dij[j,i] <= 1)  

50×50 Array{ConstraintRef{Model,C,Shape} where Shape<:AbstractShape where C,2}:
 2 dij[1,1] <= 1.0             …  dij[1,50] + dij[50,1] <= 1.0  
 dij[2,1] + dij[1,2] <= 1.0       dij[2,50] + dij[50,2] <= 1.0  
 dij[3,1] + dij[1,3] <= 1.0       dij[3,50] + dij[50,3] <= 1.0  
 dij[4,1] + dij[1,4] <= 1.0       dij[4,50] + dij[50,4] <= 1.0  
 dij[5,1] + dij[1,5] <= 1.0       dij[5,50] + dij[50,5] <= 1.0  
 dij[6,1] + dij[1,6] <= 1.0    …  dij[6,50] + dij[50,6] <= 1.0  
 dij[7,1] + dij[1,7] <= 1.0       dij[7,50] + dij[50,7] <= 1.0  
 dij[8,1] + dij[1,8] <= 1.0       dij[8,50] + dij[50,8] <= 1.0  
 dij[9,1] + dij[1,9] <= 1.0       dij[9,50] + dij[50,9] <= 1.0  
 dij[10,1] + dij[1,10] <= 1.0     dij[10,50] + dij[50,10] <= 1.0
 dij[11,1] + dij[1,11] <= 1.0  …  dij[11,50] + dij[50,11] <= 1.0
 dij[12,1] + dij[1,12] <= 1.0     dij[12,50] + dij[50,12] <= 1.0
 dij[13,1] + dij[1,13] <= 1.0     dij[13,50] + dij[50,13] <= 1.0
 ⋮                             ⋱                                
 dij[39,1]

In [26]:
optimize!(m)

In [27]:
if termination_status(m) == MOI.OPTIMAL
    optimal_solution = value.(s[1:n])
    optimal_objective = objective_value(m)
elseif termination_status(m) == MOI.TIME_LIMIT && has_values(m)
    suboptimal_solution = value.(s[1:n])
    suboptimal_objective = objective_value(m)
else
    error("The model was not solved correctly.")
end

99.0